### ISSUE TITLE
2018/11/16のメンテ以降の出撃でクライアントにエラーが出る

### ISSUE THREAD

**Issue by kPherox** [ttdoda/MyFleetGirls#15]
<del>原因は現在不明。</del>エラーは以下

```
[ERROR] [11/16/2018 22:57:22.028] [default-akka.actor.default-dispatcher-1107] [akka.actor.LocalActorRefProvider(akka://default)] guardian failed, shutting down system
java.lang.AssertionError: assertion failed: Empty mapinfo
        at scala.Predef$.assert(Predef.scala:219)
        at com.ponkotuy.data.MapInfo$.fromJson(MapInfo.scala:17)
        at com.ponkotuy.restype.MapInfo$.postables(MapInfo.scala:19)
        at com.ponkotuy.http.ControllerActor$$anonfun$receive$2.applyOrElse(PostActor.scala:66)
        at akka.actor.Actor.aroundReceive(Actor.scala:517)
        at akka.actor.Actor.aroundReceive$(Actor.scala:515)
        at com.ponkotuy.http.ControllerActor.aroundReceive(PostActor.scala:59)
        at akka.actor.ActorCell.receiveMessage(ActorCell.scala:588)
        at akka.actor.ActorCell.invoke(ActorCell.scala:557)
        at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:258)
        at akka.dispatch.Mailbox.run(Mailbox.scala:225)
        at akka.dispatch.Mailbox.exec(Mailbox.scala:235)
        at akka.dispatch.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
        at akka.dispatch.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
        at akka.dispatch.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
        at akka.dispatch.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)

[ERROR] [11/16/2018 22:57:23.909] [default-akka.actor.default-dispatcher-1107] [akka://default/user] assertion failed: Empty mapinfo
java.lang.AssertionError: assertion failed: Empty mapinfo
        at scala.Predef$.assert(Predef.scala:219)
        at com.ponkotuy.data.MapInfo$.fromJson(MapInfo.scala:17)
        at com.ponkotuy.restype.MapInfo$.postables(MapInfo.scala:19)
        at com.ponkotuy.http.ControllerActor$$anonfun$receive$2.applyOrElse(PostActor.scala:66)
        at akka.actor.Actor.aroundReceive(Actor.scala:517)
        at akka.actor.Actor.aroundReceive$(Actor.scala:515)
        at com.ponkotuy.http.ControllerActor.aroundReceive(PostActor.scala:59)
        at akka.actor.ActorCell.receiveMessage(ActorCell.scala:588)
        at akka.actor.ActorCell.invoke(ActorCell.scala:557)
        at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:258)
        at akka.dispatch.Mailbox.run(Mailbox.scala:225)
        at akka.dispatch.Mailbox.exec(Mailbox.scala:235)
        at akka.dispatch.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
        at akka.dispatch.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
        at akka.dispatch.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
        at akka.dispatch.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)

[INFO] [11/16/2018 22:57:25.286] [default-akka.actor.default-dispatcher-1108] [akka://default/user/controller] Message [com.ponkotuy.parser.Query] without sender to Actor[akka://default/user/controller#836613326] was not delivered. [1] dead letters encountered. If this is not an expected behavior, then [Actor[akka://default/user/controller#836613326]] may have terminated unexpectedly, This logging can be turned off or adjusted with configuration settings 'akka.log-dead-letters' and 'akka.log-dead-letters-during-shutdown'.
[INFO] [11/16/2018 22:57:25.288] [default-akka.actor.default-dispatcher-1108] [akka://default/user/controller] Message [com.ponkotuy.parser.Query] without sender to Actor[akka://default/user/controller#836613326] was not delivered. [2] dead letters encountered. If this is not an expected behavior, then [Actor[akka://default/user/controller#836613326]] may have terminated unexpectedly, This logging can be turned off or adjusted with configuration settings 'akka.log-dead-letters' and 'akka.log-dead-letters-during-shutdown'.
```

**Comment by kPherox** [comment]
MapInfoで想定している構造は以下のような構造
```json
"api_map_info": [
  {
    "api_id": "Int",
    "api_cleared": "Int",
    "api_exboss_flag": "Int",
    "api_defeat_count": "Option[Int]",
    "api_eventmap": {
      "api_now_maphp": "Option[Int]",
      "api_max_maphp": "Option[Int]",
      "api_state": "Int",
      "api_selected_rank": "Option[Int]"
    }
  }
]
```

しかしメンテ後は以下のようになっており`api_exboss_flag`が消え、`api_required_defeat_count`と`api_gauge_type`、`api_gauge_num`が追加されている
以下抜粋したjson
```json
"api_map_info": [
  {
    "api_id" : 11,
    "api_cleared" : 1
  }, {
    "api_id" : 15,
    "api_cleared" : 1,
    "api_gauge_type" : 1,
    "api_gauge_num" : 1
  }, {
    "api_id" : 55,
    "api_cleared" : 0,
    "api_defeat_count" : 0,
    "api_required_defeat_count" : 5,
    "api_gauge_type" : 1,
    "api_gauge_num" : 1
  }, {
    "api_id" : 64,
    "api_cleared" : 1,
    "api_gauge_type" : 1,
    "api_gauge_num" : 1,
    "api_air_base_decks" : 1
  }
]
```

MFGのサーバーで`api_exboss_flag`を利用しているのは確認できないので削除することで解決できると思う
