### ISSUE TITLE
海風改二が登録されない

### ISSUE THREAD

**Issue by kema8351** [ttdoda/MyFleetGirls#32]
海風改二がMyFleetGirlsに登録されないようです。
海風改のページに改造先が表示されていません。
https://myfleet.moe/entire/sta/book/350

クライアント側からstart2レスポンスが送信されていないのが原因に見えます。

ここからはクライアントに表示されたスタックトレースからの予想ですが、
以下のPRのようにEquipTypeの46番を追加すれば解決するかもしれません。
https://github.com/ponkotuy/MyFleetGirls/pull/363

6/25のメンテナンスで以下の2つの装備が追加されたようです。
　id344 九七式艦攻改 試製三号戊型(空六号電探改装備機)
　id345 九七式艦攻改(熟練) 試製三号戊型(空六号電探改装備機)
start2のJsonを見ると、これらのEquipTypeが46です（多分）。
https://github.com/ttdoda/MyFleetGirls/blob/master/server/app/tool/EquipType.scala
に登録されているのは45番までです。

**Comment by kPherox** [comment]
server側にそもそも海風改二の情報が送られてないのでstart2の中身が変わったって考える方が良さそう
エラーでは
https://github.com/ttdoda/MyFleetGirls/blob/master/library/src/main/scala/com/ponkotuy/data/master/MasterSlotItem.scala#L33
で`JNothing`と言ってるので`api_info`が無くなったのではないか

```スタックトレース
11:15:57 [default-akka.actor.default-dispatcher-1051] ERROR c.p.h.ControllerActor - Poster Errorscala.MatchError: JNothing (of class org.json4s.JsonAST$JNothing$)
	at com.ponkotuy.data.master.MasterSlotItem$.$anonfun$fromJson$1(MasterSlotItem.scala:33)
	at scala.collection.immutable.List.map(List.scala:282)
	at com.ponkotuy.data.master.MasterSlotItem$.fromJson(MasterSlotItem.scala:19)
	at com.ponkotuy.restype.ApiStart2$.masterSlotitem(ApiStart2.scala:58)
	at com.ponkotuy.restype.ApiStart2$.postablesFromJValue(ApiStart2.scala:32)
	at com.ponkotuy.restype.ApiStart2$.postables(ApiStart2.scala:24)
	at com.ponkotuy.http.ControllerActor$$anonfun$receive$2.applyOrElse(PostActor.scala:66)
	at akka.actor.Actor.aroundReceive(Actor.scala:517)
	at akka.actor.Actor.aroundReceive$(Actor.scala:515)
	at com.ponkotuy.http.ControllerActor.aroundReceive(PostActor.scala:59)
	at akka.actor.ActorCell.receiveMessage(ActorCell.scala:588)
	at akka.actor.ActorCell.invoke(ActorCell.scala:557)
	at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:258)
	at akka.dispatch.Mailbox.run(Mailbox.scala:225)
	at akka.dispatch.Mailbox.exec(Mailbox.scala:235)
	at akka.dispatch.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
	at akka.dispatch.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
	at akka.dispatch.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
	at akka.dispatch.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
```

**Comment by kema8351** [comment]
確かに！ api_infoが消えているので、それが原因ですね。

別のMasterSlotItem.scalaを見てて気づきませんでした。お恥ずかしい。
https://github.com/ttdoda/MyFleetGirls/blob/master/server/app/models/db/MasterSlotItem.scala

**Comment by ttdoda** [comment]
ありがとうございます。メンテに入ったのでテスト環境でしか試していませんが、正しく動いています。
